CREATE SEQUENCE entity_master_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 999999999999999999
CACHE 1000
NOCYCLE;

CREATE OR REPLACE TRIGGER Trg_Entity_Master_id
BEFORE INSERT ON entity_master
FOR EACH ROW
BEGIN
 IF :NEW.user_id IS NULL THEN
    SELECT entity_master_seq.sequence.NEXTVAL
    INTO :NEW.user_id
    FROM DUAL;
 END IF;
END;
/

DESC ENTITY_MASTER;